### ISSUE TITLE
Question: multiple NSManagedObjectContexts

### ISSUE THREAD

**Issue by VGraupera** [macfanatic/motion_data_wrapper#1]
These wrappers look awesome. 

Question: how would you use them if you need to have more than 1 NSManagedObjectContext e.g. one shared on on the main thread and another in a background thread?

Thanks.

**Comment by macfanatic** [comment]
When supporting multiple contexts, there are a few things to keep in mind:
1. If you have relationships, instances need to be in the same context or exceptions will be raised
2. Some methods such as `#create` and `#create!` automatically insert objects into the main context, defined on `App.delegate` via an included module (per normal Apple template when creating a new CoreData based project).
3. There is currently not a way to query objects & retrieve them into a context other than the main context.

To support querying into another context, we would need to add some support in making this method more robust & allow configuration somehow: https://github.com/macfanatic/motion_data_wrapper/blob/master/lib/motion_data_wrapper/relation/core_data.rb#L16

For creating instances, I would do the following:

``` ruby
# some other context you want to use...
bg_ctx = ...

company = Company.new name: 'Great Company'
customer = Customer.new first_name: 'Matt', last_name: 'Brewer', company: company

# instances are not in a context currently, only inserted into a context when attempting to persist
company.insertIntoManagedObjectContext(bg_ctx)
customer.insertIntoManagedObjectContext(bg_ctx)

# since the instances are now in a context, calling `#save` will not insert them into the main context, it will just try to save the context itself
company.save
```

If you'd like to create a PR to allow querying into a specified context, that'd be great!
