### ISSUE TITLE
undefined method `delegate' for nil:NilClass (app.rb:58)

### ISSUE THREAD

**Issue by Pasta** [macfanatic/motion_data_wrapper#18]
Hello,

I followed all the instructions on the readme but I still have this:

app.rb:58:in `delegate': undefined method`delegate' for nil:NilClass (NoMethodError)
    from core_data.rb:12:in `entity_description'
    from persistence.rb:26:in`new:'

The app is pretty fresh, no crazy gems used, only bubble wrap and ib. 

It looks like the  App is called during class loading, but is not defined yet.

Cheers,

**Comment by jamonholmgren** [comment]
Could you post your code?

**Comment by Pasta** [comment]
Okay I found the problem.

I was instantiating MotionDataWrapper::Model's outside of the scope of any method of an instance. Basically, For testing purposes, I was creating constant values of MotionDataWrapper::Model's.

Those methods were then called during class loading, and thus, App was not defined yet. 

Duh, I was on the right path, but maybe I was too tired to see the guilty lines.

I guess we can close that issue.

Cheers,

**Comment by macfanatic** [comment]
Glad you figured it out, thanks for posting the solution for others to find!
