### ISSUE TITLE
Associating an object to several others

### ISSUE THREAD

**Issue by james246** [macfanatic/motion_data_wrapper#19]
When I associate an object with several other objects (which have a to-one relationship set), only the object to have its relationship set last retains a pointer to the related object.

```
b = Bar.new

f = Foo.new
f.bar = b
f.save
f.bar
# => #<Bar:0x15084090>

f2 = Foo.new
f2.bar = b
f2.save
f2.bar
# => #<Bar:0x15084090>

f.bar
# => nil

```

Is this just how Core Data works? Only allowing an object to be associated with one other, when using a to-one relationship? I want several Foos to relate to one Bar, but not have to set up a many-to-many relationship through a FooBars entity. Is it possible?

**Comment by macfanatic** [comment]
@james246 - Could you at least post a screenshot of the applicable CoreData modeler relationships & entities?

From what I see above, I'm assuming that you have your `Foo#bar` relationship configured as a one to one, and it should be a one to many - `Bar` can have many `foo` objects, but a `Foo` only belongs to one bar.  That is all doable & configured in the data modeler for the properties of that relationship.

**Comment by james246** [comment]
Yes, you are absolutely right. I had the Foo -> Bar relationship as to-one, but critically, not the Bar -> Foo as to-many. Thanks for the pointer, I've been scratching my head over that for a bit too long. Feel free to delete this Issue!

P.S. Great work on motion_data_wrapper, enjoying using it for my first RubyMotion project :)

**Comment by macfanatic** [comment]
Great, glad it was easy to resolve on your end in the modeler, thanks @james246!
