### ISSUE TITLE
iCloud Support

### ISSUE THREAD

**Issue by pixlwave** [macfanatic/motion_data_wrapper#20]
Hi. Any chance of iCloud sync being added to this gem? I'm really enjoying using the simple syntax that motion_data_wrapper provides, but I've become stuck implementing sync on top of it. Many thanks :)

**Comment by macfanatic** [comment]
Hey @digitalfx - I haven't used iCloud sync in my personal projects at all or researched what would go into this, so probably not.

Would love to hear how you've put it in place on top of this gem, that might enlighten me and show a path that we could take. Would you might sharing some on here?

**Comment by pixlwave** [comment]
Well I was just trying to use it with some cocoapods. The only iCloud one I got anywhere with was [Ensembles](https://github.com/drewmccormack/ensembles) that let me set up the ensemble, but trying to 'leech' and merge ended up in errors.

This was how I set up my app delegate with it:

```
def setupEnsembles

  @cloudFileSystem = CDEICloudFileSystem.alloc.initWithUbiquityContainerIdentifier(nil)
  @ensemble = CDEPersistentStoreEnsemble.alloc.initWithEnsembleIdentifier("MainStore", persistentStoreURL:sqlite_url, managedObjectModelURL:NSBundle.mainBundle.URLForResource("Model", withExtension:"momd"), cloudFileSystem:@cloudFileSystem)
  @ensemble.delegate = self

  unless @ensemble.isLeeched
    @ensemble.leechPersistentStoreWithCompletion(lambda { |error|
      NSLog "Could not leech to ensemble #{error}" if error
      NSLog "Reason #{error.localizedFailureReason}" if error
    })
  end

  @ensemble.mergeWithCompletion(lambda { |error|
    NSLog "Error merging: #{error}" if error
  })

end

def persistentStoreEnsemble(ensemble, didSaveMergeChangesWithNotification: notification)

  managedObjectContext.performBlock(lambda {
    managedObjectContext.mergeChangesFromContextDidSaveNotification(notification)
  })

end
```

And I added this to my rakefile:

```
app.identifier = 'com.company.myappname'
app.seed_id = '########'
app.provisioning_profile = 'certificates/appwithicloud.mobileprovision'

app.entitlements['application-identifier'] = "#{app.seed_id}.#{app.identifier}"
app.entitlements['com.apple.developer.ubiquity-container-identifiers'] = ["#{app.seed_id}.#{app.identifier}"]
```

**Comment by pixlwave** [comment]
I have managed to get [ParcelKit](https://github.com/overcommitted/ParcelKit) working (syncs via dropbox), however I only managed to compile it into an iOS app and not an OS X app, and really I'd prefer iCloud sync.
