### ISSUE TITLE
Relationship class

### ISSUE THREAD

**Issue by pixlwave** [macfanatic/motion_data_wrapper#21]
Hi. Not sure if I'm missing something but I've run into a problem. Let's say I have two objects, Team and Player. So my Model can contain multiple Teams each with multiple players. I was expecting the following code to work:

`playersArray = Team.first.players.order(:lastName).all`

However, instead I get an `undefined method 'order'` error. After investigating this, it seems that `Team.first.players` returns an NSFaultingMutableSet and not an MotionDataWrapper::Relation object. Is there a correct way to do this?

Many thanks

**Comment by macfanatic** [comment]
Basically `Team.first` is giving you a plain `NSManagedObject` subclass, and this gem doesn't give you any chaining in associations like that.

If you really wanted to use the gem for the query, you'd have to do something such as (forgive me, it's been a long time since I've used this gem now)

``` ruby
Player.where("team = ?", Team.first).order(:lastName).all
```

**Comment by pixlwave** [comment]
Ah right, that makes sense. Thanks
